server: 
  port: 8081
  node: 
    name: web
spring:
  application: 
    name: web
  profiles: 
    active: default
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/crawler?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: 
    serialization: 
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
  servlet: 
    multipart: 
      max-file-size: 4MB
  redis: 
    client-name: rds02
    host: localhost
    port: 6379
  cache: 
    redis:
      time-to-live: 14400000
  session: 
    timeout: 30m
    store-type: redis
    redis: 
      namespace: "session"